<?php

namespace Container04qEQqd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FoeC1S9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FoeC1S9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FoeC1S9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repositoryV' => ['privates', 'App\\Repository\\MarqueVehiculeRepository', 'getMarqueVehiculeRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'repositoryV' => 'App\\Repository\\MarqueVehiculeRepository',
            'serializer' => '?',
        ]);
    }
}
