<?php

namespace Container04qEQqd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bo6LrAmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bo6LrAm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bo6LrAm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repositoryModeleTest' => ['privates', 'App\\Repository\\ModeleTestRepository', 'getModeleTestRepositoryService', true],
            'repositoryMonType' => ['privates', 'App\\Repository\\MonTypeTRepository', 'getMonTypeTRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'repositoryModeleTest' => 'App\\Repository\\ModeleTestRepository',
            'repositoryMonType' => 'App\\Repository\\MonTypeTRepository',
            'serializer' => '?',
        ]);
    }
}
