<?php

namespace Container04qEQqd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Vkx0CD5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vkx0CD5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vkx0CD5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repository' => ['privates', 'App\\Repository\\ModeleTestRepository', 'getModeleTestRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'validator' => ['privates', 'validator', 'getValidatorService', false],
        ], [
            'entityManager' => '?',
            'repository' => 'App\\Repository\\ModeleTestRepository',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
