<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVOP03xC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVOP03xC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVOP03xC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVOP03xC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVOP03xC\App_KernelDevDebugContainer([
    'container.build_hash' => 'VOP03xC',
    'container.build_id' => '265971b8',
    'container.build_time' => 1705571107,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVOP03xC');
