<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIJ7Tml8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIJ7Tml8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIJ7Tml8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIJ7Tml8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIJ7Tml8\App_KernelDevDebugContainer([
    'container.build_hash' => 'IJ7Tml8',
    'container.build_id' => 'ad8fa0ae',
    'container.build_time' => 1705653483,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIJ7Tml8');
