<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container04qEQqd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container04qEQqd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container04qEQqd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container04qEQqd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container04qEQqd\App_KernelDevDebugContainer([
    'container.build_hash' => '04qEQqd',
    'container.build_id' => '1bf6d082',
    'container.build_time' => 1705565905,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container04qEQqd');
